version: '3.4'

networks:
  dockerapi-dev:
    driver: bridge

services:
  api:
    image: api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_URLS: "http://+:8000"
    networks:
      - dockerapi-dev

  app:
    container_name: front
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: "production"
    volumes:
      - ./logs/:/app/logs
      - ./assets:/app/assets
    restart: always
    networks:
      - dockerapi-dev
volumes:
  db_volume:
